description: 'ReDoc app to generate OpenAPI/Swagger documentation'
screenshot: 'https://raw.githubusercontent.com/apioo/fusio/master/doc/_static/redoc.png'
website: 'https://github.com/apioo/fusio-apps-redoc'